__author__ = 'Justin Crawford'

# Data from http://www.ptable.com/
PeriodicTable = [
	{"Hydrogen":      {"AtomicNum": 1,   "Symbol": "H",   "Weight": 1.008,       "State": "Gas",     "Type": "Other Non-Metal"}},
	{"Helium":        {"AtomicNum": 2,   "Symbol": "He",  "Weight": 2.002602,    "State": "Gas",     "Type": "Noble Gas"}},
	{"Lithium":       {"AtomicNum": 3,   "Symbol": "Li",  "Weight": 6.94,        "State": "Solid",   "Type": "Alkali Metal"}},
	{"Beryllium":     {"AtomicNum": 4,   "Symbol": "H",   "Weight": 9.012182,    "State": "Solid",   "Type": "Alkaline Earth Metal"}},
	{"Boron":         {"AtomicNum": 5,   "Symbol": "B",   "Weight": 10.81,       "State": "Solid",   "Type": "Metalloid"}},
	{"Carbon":        {"AtomicNum": 6,   "Symbol": "C",   "Weight": 12.011,      "State": "Solid",   "Type": "Other Non-Metal"}},
	{"Nitrogen":      {"AtomicNum": 7,   "Symbol": "N",   "Weight": 14.007,      "State": "Gas",     "Type": "Other Non-Metal"}},
	{"Oxygen":        {"AtomicNum": 8,   "Symbol": "O",   "Weight": 15.999,      "State": "Gas",     "Type": "Other Non-Metal"}},
	{"Fluorine":      {"AtomicNum": 9,   "Symbol": "F",   "Weight": 18.9984032,  "State": "Gas",     "Type": "Halogen"}},
	{"Neon":          {"AtomicNum": 10,  "Symbol": "Ne",  "Weight": 20.1797,     "State": "Gas",     "Type": "Noble Gas"}},
	{"Sodium":        {"AtomicNum": 11,  "Symbol": "Na",  "Weight": 22.98976928, "State": "Solid",   "Type": "Alkali Metal"}},
	{"Magnesium":     {"AtomicNum": 12,  "Symbol": "Mg",  "Weight": 24.305,      "State": "Solid",   "Type": "Alkaline Earth Metal"}},
	{"Aluminum":      {"AtomicNum": 13,  "Symbol": "Al",  "Weight": 26.9815386,  "State": "Solid",   "Type": "Post-transition Metal"}},
	{"Silicon":       {"AtomicNum": 14,  "Symbol": "Si",  "Weight": 28.085,      "State": "Solid",   "Type": "Metalloid"}},
	{"Phosphorus":    {"AtomicNum": 15,  "Symbol": "P",   "Weight": 30.973762,   "State": "Solid",   "Type": "Other Non-Metal"}},
	{"Sulfur":        {"AtomicNum": 16,  "Symbol": "S",   "Weight": 32.06,       "State": "Solid",   "Type": "Other Non-Metal"}},
	{"Chlorine":      {"AtomicNum": 17,  "Symbol": "Cl",  "Weight": 35.45,       "State": "Gas",     "Type": "Halogen"}},
	{"Argon":         {"AtomicNum": 18,  "Symbol": "Ar",  "Weight": 39.948,      "State": "Gas",     "Type": "Noble Gas"}},
	{"Potassium":     {"AtomicNum": 19,  "Symbol": "K",   "Weight": 39.0983,     "State": "Solid",   "Type": "Alkali Metal"}},
	{"Calcium":       {"AtomicNum": 20,  "Symbol": "Ca",  "Weight": 40.078,      "State": "Solid",   "Type": "Alkaline Earth Metal"}},
	{"Scandium":      {"AtomicNum": 21,  "Symbol": "Sc",  "Weight": 44.955912,   "State": "Solid",   "Type": "Transition Metal"}},
	{"Titanium":      {"AtomicNum": 22,  "Symbol": "Ti",  "Weight": 47.867,      "State": "Solid",   "Type": "Transition Metal"}},
	{"Vanadium":      {"AtomicNum": 23,  "Symbol": "V",   "Weight": 50.9415,     "State": "Solid",   "Type": "Transition Metal"}},
	{"Chromium":      {"AtomicNum": 24,  "Symbol": "Cr",  "Weight": 51.9961,     "State": "Solid",   "Type": "Transition Metal"}},
	{"Manganese":     {"AtomicNum": 25,  "Symbol": "Mn",  "Weight": 54.938045,   "State": "Solid",   "Type": "Transition Metal"}},
	{"Iron":          {"AtomicNum": 26,  "Symbol": "Fe",  "Weight": 55.845,      "State": "Solid",   "Type": "Transition Metal"}},
	{"Cobalt":        {"AtomicNum": 27,  "Symbol": "Co",  "Weight": 58.933195,   "State": "Solid",   "Type": "Transition Metal"}},
	{"Nickel":        {"AtomicNum": 28,  "Symbol": "Ni",  "Weight": 58.6934,     "State": "Solid",   "Type": "Transition Metal"}},
	{"Copper":        {"AtomicNum": 29,  "Symbol": "Cu",  "Weight": 63.546,      "State": "Solid",   "Type": "Transition Metal"}},
	{"Zinc":          {"AtomicNum": 30,  "Symbol": "Zn",  "Weight": 65.38,       "State": "Solid",   "Type": "Transition Metal"}},
	{"Gallium":       {"AtomicNum": 31,  "Symbol": "Ga",  "Weight": 69.723,      "State": "Solid",   "Type": "Post-transition Metal"}},
	{"Germanium":     {"AtomicNum": 32,  "Symbol": "Ge",  "Weight": 72.63,       "State": "Solid",   "Type": "Metalloid"}},
	{"Arsenic":       {"AtomicNum": 33,  "Symbol": "As",  "Weight": 74.92160,    "State": "Solid",   "Type": "Metalloid"}},
	{"Selenium":      {"AtomicNum": 34,  "Symbol": "Se",  "Weight": 78.96,       "State": "Solid",   "Type": "Other Non-Metal"}},
	{"Bromine":       {"AtomicNum": 35,  "Symbol": "Br",  "Weight": 79.904,      "State": "Liquid",  "Type": "Halogen"}},
	{"Krypton":       {"AtomicNum": 36,  "Symbol": "Kr",  "Weight": 83.798,      "State": "Gas",     "Type": "Noble Gas"}},
	{"Rubidium":      {"AtomicNum": 37,  "Symbol": "Rb",  "Weight": 85.4678,     "State": "Solid",   "Type": "Alkali Metal"}},
	{"Strontium":     {"AtomicNum": 38,  "Symbol": "Sr",  "Weight": 87.62,       "State": "Solid",   "Type": "Alkaline Earth Metal"}},
	{"Yttrium":       {"AtomicNum": 39,  "Symbol": "Y",   "Weight": 88.90585,    "State": "Solid",   "Type": "Transition Metal"}},
	{"Zirconium":     {"AtomicNum": 40,  "Symbol": "Zr",  "Weight": 91.224,      "State": "Solid",   "Type": "Transition Metal"}},
	{"Niobium":       {"AtomicNum": 41,  "Symbol": "Nb",  "Weight": 92.90638,    "State": "Solid",   "Type": "Transition Metal"}},
	{"Molybdenum":    {"AtomicNum": 42,  "Symbol": "Mo",  "Weight": 95.96,       "State": "Solid",   "Type": "Transition Metal"}},
	{"Technetium":    {"AtomicNum": 43,  "Symbol": "Tc",  "Weight": 98,          "State": "Solid",   "Type": "Transition Metal"}},
	{"Ruthenium":     {"AtomicNum": 44,  "Symbol": "Ru",  "Weight": 101.07,      "State": "Solid",   "Type": "Transition Metal"}},
	{"Rhodium":       {"AtomicNum": 45,  "Symbol": "Rh",  "Weight": 102.90550,   "State": "Solid",   "Type": "Transition Metal"}},
	{"Palladium":     {"AtomicNum": 46,  "Symbol": "Pd",  "Weight": 106.42,      "State": "Solid",   "Type": "Transition Metal"}},
	{"Silver":        {"AtomicNum": 47,  "Symbol": "Ag",  "Weight": 107.8682,    "State": "Solid",   "Type": "Transition Metal"}},
	{"Cadmium":       {"AtomicNum": 48,  "Symbol": "Cd",  "Weight": 112.411,     "State": "Solid",   "Type": "Transition Metal"}},
	{"Indium":        {"AtomicNum": 49,  "Symbol": "In",  "Weight": 114.818,     "State": "Solid",   "Type": "Post-transition Metal"}},
	{"Tin":           {"AtomicNum": 50,  "Symbol": "Sn",  "Weight": 118.710,     "State": "Solid",   "Type": "Post-transition Metal"}},
	{"Antimony":      {"AtomicNum": 51,  "Symbol": "Sb",  "Weight": 121.760,     "State": "Solid",   "Type": "Metalloid"}},
	{"Tellurium":     {"AtomicNum": 52,  "Symbol": "Te",  "Weight": 127.60,      "State": "Solid",   "Type": "Metalloid"}},
	{"Iodine":        {"AtomicNum": 53,  "Symbol": "I",   "Weight": 126.90447,   "State": "Solid",   "Type": "Halogen"}},
	{"Xenon":         {"AtomicNum": 54,  "Symbol": "Xe",  "Weight": 131.293,     "State": "Gas",     "Type": "Noble Gas"}},
	{"Caesium":       {"AtomicNum": 55,  "Symbol": "Cs",  "Weight": 132.9054519, "State": "Solid",   "Type": "Alkali Metal"}},
	{"Barium":        {"AtomicNum": 56,  "Symbol": "Ba",  "Weight": 137.327,     "State": "Solid",   "Type": "Alkaline Earth Metal"}},
	{"Lanthanum":     {"AtomicNum": 57,  "Symbol": "La",  "Weight": 138.90547,   "State": "Solid",   "Type": "Lanthanoid"}},
	{"Cerium":        {"AtomicNum": 58,  "Symbol": "Ce",  "Weight": 140.116,     "State": "Solid",   "Type": "Lanthanoid"}},
	{"Praseodymium":  {"AtomicNum": 59,  "Symbol": "Pr",  "Weight": 140.90765,   "State": "Solid",   "Type": "Lanthanoid"}},
	{"Neodymium":     {"AtomicNum": 60,  "Symbol": "Nd",  "Weight": 144.242,     "State": "Solid",   "Type": "Lanthanoid"}},
	{"Promethium":    {"AtomicNum": 61,  "Symbol": "Pm",  "Weight": 145,         "State": "Solid",   "Type": "Lanthanoid"}},
	{"Samarium":      {"AtomicNum": 62,  "Symbol": "Sm",  "Weight": 150.36,      "State": "Solid",   "Type": "Lanthanoid"}},
	{"Europium":      {"AtomicNum": 63,  "Symbol": "Eu",  "Weight": 151.964,     "State": "Solid",   "Type": "Lanthanoid"}},
	{"Gadolinium":    {"AtomicNum": 64,  "Symbol": "Gd",  "Weight": 157.25,      "State": "Solid",   "Type": "Lanthanoid"}},
	{"Terbium":       {"AtomicNum": 65,  "Symbol": "Tb",  "Weight": 158.92535,   "State": "Solid",   "Type": "Lanthanoid"}},
	{"Dysprosium":    {"AtomicNum": 66,  "Symbol": "Dy",  "Weight": 162.500,     "State": "Solid",   "Type": "Lanthanoid"}},
	{"Holmium":       {"AtomicNum": 67,  "Symbol": "Ho",  "Weight": 164.93032,   "State": "Solid",   "Type": "Lanthanoid"}},
	{"Erbium":        {"AtomicNum": 68,  "Symbol": "Er",  "Weight": 167.259,     "State": "Solid",   "Type": "Lanthanoid"}},
	{"Thulium":       {"AtomicNum": 69,  "Symbol": "Tm",  "Weight": 168.93421,   "State": "Solid",   "Type": "Lanthanoid"}},
	{"Ytterbium":     {"AtomicNum": 70,  "Symbol": "Yb",  "Weight": 173.054,     "State": "Solid",   "Type": "Lanthanoid"}},
	{"Lutetium":      {"AtomicNum": 71,  "Symbol": "Lu",  "Weight": 174.9668,    "State": "Solid",   "Type": "Lanthanoid"}},
	{"Hafnium":       {"AtomicNum": 72,  "Symbol": "Hf",  "Weight": 178.49,      "State": "Solid",   "Type": "Transition Metal"}},
	{"Tantalum":      {"AtomicNum": 73,  "Symbol": "Ta",  "Weight": 180.94788,   "State": "Solid",   "Type": "Transition Metal"}},
	{"Tungsten":      {"AtomicNum": 74,  "Symbol": "W",   "Weight": 183.84,      "State": "Solid",   "Type": "Transition Metal"}},
	{"Rhenium":       {"AtomicNum": 75,  "Symbol": "Re",  "Weight": 186.207,     "State": "Solid",   "Type": "Transition Metal"}},
	{"Osmium":        {"AtomicNum": 76,  "Symbol": "Os",  "Weight": 190.23,      "State": "Solid",   "Type": "Transition Metal"}},
	{"Iridium":       {"AtomicNum": 77,  "Symbol": "Ir",  "Weight": 192.217,     "State": "Solid",   "Type": "Transition Metal"}},
	{"Platinum":      {"AtomicNum": 78,  "Symbol": "Pt",  "Weight": 195.084,     "State": "Solid",   "Type": "Transition Metal"}},
	{"Gold":          {"AtomicNum": 79,  "Symbol": "Au",  "Weight": 196.966569,  "State": "Solid",   "Type": "Transition Metal"}},
	{"Mercury":       {"AtomicNum": 80,  "Symbol": "Hg",  "Weight": 200.59,      "State": "Liquid",  "Type": "Transition Metal"}},
	{"Thallium":      {"AtomicNum": 81,  "Symbol": "Tl",  "Weight": 204.38,      "State": "Solid",   "Type": "Post-transition Metal"}},
	{"Lead":          {"AtomicNum": 82,  "Symbol": "Pb",  "Weight": 207.2,       "State": "Solid",   "Type": "Post-transition Metal"}},
	{"Bismuth":       {"AtomicNum": 83,  "Symbol": "Bi",  "Weight": 208.98040,   "State": "Solid",   "Type": "Post-transition Metal"}},
	{"Polonium":      {"AtomicNum": 84,  "Symbol": "Po",  "Weight": 209,         "State": "Solid",   "Type": "Metalloid"}},
	{"Astatine":      {"AtomicNum": 85,  "Symbol": "At",  "Weight": 210,         "State": "Solid",   "Type": "Halogen"}},
	{"Radon":         {"AtomicNum": 86,  "Symbol": "Rn",  "Weight": 222,         "State": "Gas",     "Type": "Noble Gas"}},
	{"Francium":      {"AtomicNum": 87,  "Symbol": "Fr",  "Weight": 223,         "State": "Solid",   "Type": "Alkali Metal"}},
	{"Radium":        {"AtomicNum": 88,  "Symbol": "Ra",  "Weight": 226,         "State": "Solid",   "Type": "Alkaline Earth Metal"}},
	{"Actinium":      {"AtomicNum": 89,  "Symbol": "Ac",  "Weight": 227,         "State": "Solid",   "Type": "Actinoid"}},
	{"Thorium":       {"AtomicNum": 90,  "Symbol": "Th",  "Weight": 232.03806,   "State": "Solid",   "Type": "Actinoid"}},
	{"Protactinium":  {"AtomicNum": 91,  "Symbol": "Pa",  "Weight": 231.03588,   "State": "Solid",   "Type": "Actinoid"}},
	{"Uranium":       {"AtomicNum": 92,  "Symbol": "U",   "Weight": 238.02891,   "State": "Solid",   "Type": "Actinoid"}},
	{"Neptunium":     {"AtomicNum": 93,  "Symbol": "Np",  "Weight": 237,         "State": "Solid",   "Type": "Actinoid"}},
	{"Plutonium":     {"AtomicNum": 94,  "Symbol": "Pu",  "Weight": 244,         "State": "Solid",   "Type": "Actinoid"}},
	{"Americium":     {"AtomicNum": 95,  "Symbol": "Am",  "Weight": 243,         "State": "Solid",   "Type": "Actinoid"}},
	{"Curium":        {"AtomicNum": 96,  "Symbol": "Cm",  "Weight": 247,         "State": "Solid",   "Type": "Actinoid"}},
	{"Berkelium":     {"AtomicNum": 97,  "Symbol": "Bk",  "Weight": 247,         "State": "Solid",   "Type": "Actinoid"}},
	{"Californium":   {"AtomicNum": 98,  "Symbol": "Cf",  "Weight": 251,         "State": "Solid",   "Type": "Actinoid"}},
	{"Einsteinium":   {"AtomicNum": 99,  "Symbol": "Es",  "Weight": 252,         "State": "Solid",   "Type": "Actinoid"}},
	{"Fermium":       {"AtomicNum": 100, "Symbol": "Fm",  "Weight": 257,         "State": "Solid",   "Type": "Actinoid"}},
	{"Mendelevium":   {"AtomicNum": 101, "Symbol": "Md",  "Weight": 258,         "State": "Solid",   "Type": "Actinoid"}},
	{"Nobelium":      {"AtomicNum": 102, "Symbol": "No",  "Weight": 259,         "State": "Solid",   "Type": "Actinoid"}},
	{"Lawrencium":    {"AtomicNum": 103, "Symbol": "Lr",  "Weight": 262,         "State": "Solid",   "Type": "Actinoid"}},
	{"Rutherfordium": {"AtomicNum": 104, "Symbol": "Rf",  "Weight": 267,         "State": "Unknown", "Type": "Transition Metal"}},
	{"Dubnium":       {"AtomicNum": 105, "Symbol": "Db",  "Weight": 268,         "State": "Unknown", "Type": "Transition Metal"}},
	{"Seaborgium":    {"AtomicNum": 106, "Symbol": "Sg",  "Weight": 271,         "State": "Unknown", "Type": "Transition Metal"}},
	{"Bohrium":       {"AtomicNum": 107, "Symbol": "Bh",  "Weight": 272,         "State": "Unknown", "Type": "Transition Metal"}},
	{"Hassium":       {"AtomicNum": 108, "Symbol": "Hs",  "Weight": 270,         "State": "Unknown", "Type": "Transition Metal"}},
	{"Meitnerium":    {"AtomicNum": 109, "Symbol": "Mt",  "Weight": 276,         "State": "Unknown", "Type": "Transition Metal"}},
	{"Darmstadtium":  {"AtomicNum": 110, "Symbol": "Ds",  "Weight": 281,         "State": "Unknown", "Type": "Transition Metal"}},
	{"Roentgenium":   {"AtomicNum": 111, "Symbol": "Rg",  "Weight": 280,         "State": "Unknown", "Type": "Transition Metal"}},
	{"Copernicium":   {"AtomicNum": 112, "Symbol": "Cn",  "Weight": 285,         "State": "Unknown", "Type": "Transition Metal"}},
	{"Ununtrium":     {"AtomicNum": 113, "Symbol": "Unt", "Weight": 284,         "State": "Unknown", "Type": "Post-transition Metal"}},
	{"Flerovium":     {"AtomicNum": 114, "Symbol": "Fl",  "Weight": 289,         "State": "Unknown", "Type": "Post-transition Metal"}},
	{"Ununpentium":   {"AtomicNum": 115, "Symbol": "Uup", "Weight": 288,         "State": "Unknown", "Type": "Post-transition Metal"}},
	{"Livermorium":   {"AtomicNum": 116, "Symbol": "Lv",  "Weight": 293,         "State": "Unknown", "Type": "Post-transition Metal"}},
	{"Ununseptium":   {"AtomicNum": 117, "Symbol": "Uus", "Weight": 294,         "State": "Unknown", "Type": "Halogen"}},
	{"Ununoctium":    {"AtomicNum": 118, "Symbol": "Uuo", "Weight": 294,         "State": "Unknown", "Type": "Noble Gas"}},
]